// Generated by Wrangler by running `wrangler types`

interface Env {
	kis_kv: KVNamespace;
	"ak-63691813": string;
	"sk-63691813": string;
	"ak-64033412": string;
	"sk-64033412": string;
	"ak-69393152": string;
	"sk-69393152": string;
}
